global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: kraken
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - kraken-exporter:8080