apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      initContainers:
        - name: configure
          image: busybox
          command: ['sh', '-c', 'if [ ! -f /prometheus/prometheus.yml ]; then wget --header "Authorization: Bearer $ACCESS_TOKEN" -O /prometheus/prometheus.yml https://www.googleapis.com/storage/v1/b/$CONFIG_BUCKET/o/prometheus.yml?alt=media; fi']
          volumeMounts:
          - name: prometheus-storage
            mountPath: /prometheus
          env:
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: gs-storage
                key: access_token
      containers:
        - image: prom/prometheus:v2.0.0
          name: prometheus
          args:
            - '--web.enable-lifecycle'
            - '--config.file=/prometheus/prometheus.yml'
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-storage
          gcePersistentDisk:
            pdName: prometheus-disk
            fsType: ext4
