apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      initContainers:
        - name: configure
          image: busybox
          command: ['sh', '-c', 'ls -lah /var/secrets/google && if [ ! -f /prometheus/prometheus.yml ]; then wget -O /prometheus/prometheus.yml kraken-exporter-config.storage.googleapis.com/prometheus.yml; fi']
          volumeMounts:
          - name: prometheus-storage
            mountPath: /prometheus
          - name: google-storage-key
            mountPath: /var/secrets/google
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      containers:
        - image: prom/prometheus:v2.0.0
          name: prometheus
          args:
            - '--web.enable-lifecycle'
            - '--config.file=/prometheus/prometheus.yml'
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-storage
          gcePersistentDisk:
            pdName: prometheus-disk
            fsType: ext4
        - name: google-storage-key
          secret:
            secretName: storage-key