apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - image: prom/prometheus:v2.0.0
          name: prometheus
          args:
            - '--web.enable-lifecycle'
            - '--config.file=/prometheus/prometheus.yml'
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-storage
          gcePersistentDisk:
            pdName: prometheus-disk
            fsType: ext4